## Explanation for Task 2

In this task, I used the metadata file created in Task 1 to create separate DataFrames for each quarter of the year 2025.

First, I loaded the CSV file `arxiv_papers_2025.csv` using pandas. Since the arxiv ID contains the year and month information, I extracted the month from each `arxiv_id`.

After extracting the month, I divided the dataset into four quarterly DataFrames:

- Q1: January to March
- Q2: April to June
- Q3: July to September
- Q4: October to December

Then, I printed the number of papers in each quarter and checked that the total number of papers across all four quarters matched the original dataset. I also displayed the first five rows of each quarterly DataFrame to verify that the data was separated correctly.

In [15]:
# Task 2: Generating DataFrames for each quarter
import pandas as pd

df = pd.read_csv("/content/sample_data/arxiv_papers_2025.csv")

# Extracting the month from arxiv_id
df["arxiv_month"] = df["arxiv_id"].astype(str).apply(lambda x: int(x[2:4]))

print(f"Total papers loaded: {len(df)}")
print(f"\nPapers per month (from arxiv_id):")
print(df["arxiv_month"].value_counts().sort_index())
df.head()

Total papers loaded: 400

Papers per month (from arxiv_id):
arxiv_month
1     22
2     26
3     30
4     42
5     39
6     33
7     28
8     27
9     34
10    44
11    33
12    42
Name: count, dtype: int64

,arxiv_id,title,authors,author_count,summary,published,updated,primary_category,categories,pdf_url,entry_id,arxiv_month,arxiv_year_month
0,2501.16349,Risk-Informed Diffusion Transformer for Long-T...,"Junlan Chen, Pei Liu, Zihao Zhang, Hongyi Zhao...",6,Trajectory prediction methods have been widely...,2025-01-18,2025-05-28,cs.LG,"['cs.LG', 'cs.AI']",https://arxiv.org/pdf/2501.16349v2,http://arxiv.org/abs/2501.16349v2,1,2025-01
1,2501.04834,Detectability of Emission from Exoplanet Outfl...,"Riley Rosener, Michael Zhang, Jacob L. Bean",3,Photoevaporation in exoplanet atmospheres is t...,2025-01-08,2025-01-10,astro-ph.EP,"['astro-ph.EP', 'astro-ph.IM']",https://arxiv.org/pdf/2501.04834v2,http://arxiv.org/abs/2501.04834v2,1,2025-01
2,2507.08695,The optimal Padé polynomial for reconstruction...,"Bo Yu, Wenhu Liu, XiaoFeng Yang, Tong-Jie zhan...",5,The cosmography known as the Padé polynomials ...,2025-07-11,2025-07-11,astro-ph.CO,['astro-ph.CO'],https://arxiv.org/pdf/2507.08695v1,http://arxiv.org/abs/2507.08695v1,7,2025-07
3,2503.23527,Convergent Power Series for Anharmonic Chain w...,"Pedro L. Garrido, Tomasz Komorowski, Joel L. L...",4,We study the propagation of energy in one-dime...,2025-03-30,2026-01-10,math-ph,['math-ph'],https://arxiv.org/pdf/2503.23527v5,http://arxiv.org/abs/2503.23527v5,3,2025-03
4,2512.03699,Transitivity and an abelian Livsic theorem for...,"Mark Pollicott, Richard Sharp",2,We show that the abelian Livšic theorem recent...,2025-12-03,2025-12-03,math.DS,['math.DS'],https://arxiv.org/pdf/2512.03699v1,http://arxiv.org/abs/2512.03699v1,12,2025-12

In [16]:
# Q1: January – March
df_q1 = df[df["arxiv_month"].between(1, 3)].reset_index(drop=True)

# Q2: April – June
df_q2 = df[df["arxiv_month"].between(4, 6)].reset_index(drop=True)

# Q3: July – September
df_q3 = df[df["arxiv_month"].between(7, 9)].reset_index(drop=True)

# Q4: October – December
df_q4 = df[df["arxiv_month"].between(10, 12)].reset_index(drop=True)

print(f"Q1 (Jan–Mar): {len(df_q1)} papers")
print(f"Q2 (Apr–Jun): {len(df_q2)} papers")
print(f"Q3 (Jul–Sep): {len(df_q3)} papers")
print(f"Q4 (Oct–Dec): {len(df_q4)} papers")
print(f"Total:        {len(df_q1) + len(df_q2) + len(df_q3) + len(df_q4)} papers")

Q1 (Jan–Mar): 78 papers
Q2 (Apr–Jun): 114 papers
Q3 (Jul–Sep): 89 papers
Q4 (Oct–Dec): 119 papers
Total:        400 papers

In [17]:
# Displaying the first 5 rows of each quarterly DataFrame
# Showing the data for first Quarter (Jan - Mar)

print(" Q1 (January – March) ")
df_q1.head()

 Q1 (January – March)

,arxiv_id,title,authors,author_count,summary,published,updated,primary_category,categories,pdf_url,entry_id,arxiv_month,arxiv_year_month
0,2501.16349,Risk-Informed Diffusion Transformer for Long-T...,"Junlan Chen, Pei Liu, Zihao Zhang, Hongyi Zhao...",6,Trajectory prediction methods have been widely...,2025-01-18,2025-05-28,cs.LG,"['cs.LG', 'cs.AI']",https://arxiv.org/pdf/2501.16349v2,http://arxiv.org/abs/2501.16349v2,1,2025-01
1,2501.04834,Detectability of Emission from Exoplanet Outfl...,"Riley Rosener, Michael Zhang, Jacob L. Bean",3,Photoevaporation in exoplanet atmospheres is t...,2025-01-08,2025-01-10,astro-ph.EP,"['astro-ph.EP', 'astro-ph.IM']",https://arxiv.org/pdf/2501.04834v2,http://arxiv.org/abs/2501.04834v2,1,2025-01
2,2503.23527,Convergent Power Series for Anharmonic Chain w...,"Pedro L. Garrido, Tomasz Komorowski, Joel L. L...",4,We study the propagation of energy in one-dime...,2025-03-30,2026-01-10,math-ph,['math-ph'],https://arxiv.org/pdf/2503.23527v5,http://arxiv.org/abs/2503.23527v5,3,2025-03
3,2503.13908,Error correction of a logical qubit encoded in...,"Kyle DeBry, Nadine Meister, Agustin Valdes Mar...",9,Quantum error correction (QEC) is essential fo...,2025-03-18,2025-03-18,quant-ph,"['quant-ph', 'physics.atom-ph']",https://arxiv.org/pdf/2503.13908v1,http://arxiv.org/abs/2503.13908v1,3,2025-03
4,2503.12292,Existence and non-uniqueness of classical solu...,"Zijin Li, Xinghong Pan",2,"In this paper, we show existence and non-uniqu...",2025-03-15,2025-03-15,math.AP,['math.AP'],https://arxiv.org/pdf/2503.12292v1,http://arxiv.org/abs/2503.12292v1,3,2025-03

In [18]:
# Showing the data for second Quarter (Apr - Jun)

print(" Q2 (April – June) ")
df_q2.head()

 Q2 (April – June)

,arxiv_id,title,authors,author_count,summary,published,updated,primary_category,categories,pdf_url,entry_id,arxiv_month,arxiv_year_month
0,2505.22406,Complete Catalog of Laser Locking Configuratio...,"Gerhard Heinzel, Javier Álvarez-Vizoso, Miguel...",3,The Laser Interferometer Space Antenna (LISA) ...,2025-05-28,2025-05-28,physics.ins-det,"['physics.ins-det', 'astro-ph.IM', 'gr-qc', 'p...",https://arxiv.org/pdf/2505.22406v1,http://arxiv.org/abs/2505.22406v1,5,2025-05
1,2505.20780,Causal inference with dyadic data in randomize...,"Yilin Li, Lu Deng, Yong Wang, Wang Miao",4,Estimating the treatment effect within network...,2025-05-27,2025-05-27,stat.ME,"['stat.ME', 'stat.AP']",https://arxiv.org/pdf/2505.20780v1,http://arxiv.org/abs/2505.20780v1,5,2025-05
2,2506.23206,Uncentered Fractional Maximal functions and me...,"Riju Basak, You-Wei Benson Chen, Prasun Roycho...",3,We study the action of uncentered fractional m...,2025-06-29,2025-06-29,math.FA,"['math.FA', 'math.AP', 'math.CA']",https://arxiv.org/pdf/2506.23206v1,http://arxiv.org/abs/2506.23206v1,6,2025-06
3,2505.19268,On Heegaard Floer minimal knots in sutured man...,Fraser Binns,1,Li-Xie-Zhang classified instanton Floer minima...,2025-05-25,2025-05-25,math.GT,['math.GT'],https://arxiv.org/pdf/2505.19268v1,http://arxiv.org/abs/2505.19268v1,5,2025-05
4,2506.22642,DeepDive: A deep dive into the physics of the ...,"K. Ito, F. Valentino, G. Brammer, M. L. Hamado...",29,"We present the DeepDive program, in which we o...",2025-06-27,2025-06-27,astro-ph.GA,['astro-ph.GA'],https://arxiv.org/pdf/2506.22642v1,http://arxiv.org/abs/2506.22642v1,6,2025-06

In [19]:
# Showing the data for third Quarter (Jul - Sep)

print(" Q3 (July – September) ")
df_q3.head()

 Q3 (July – September)

,arxiv_id,title,authors,author_count,summary,published,updated,primary_category,categories,pdf_url,entry_id,arxiv_month,arxiv_year_month
0,2507.08695,The optimal Padé polynomial for reconstruction...,"Bo Yu, Wenhu Liu, XiaoFeng Yang, Tong-Jie zhan...",5,The cosmography known as the Padé polynomials ...,2025-07-11,2025-07-11,astro-ph.CO,['astro-ph.CO'],https://arxiv.org/pdf/2507.08695v1,http://arxiv.org/abs/2507.08695v1,7,2025-07
1,2509.11217,Frustration-Enhanced Quantum Annealing Correct...,"Tomohiro Hattori, Shu Tanaka",2,Quantum annealing correction (QAC) models prov...,2025-09-14,2025-09-14,cond-mat.stat-mech,"['cond-mat.stat-mech', 'quant-ph']",https://arxiv.org/pdf/2509.11217v1,http://arxiv.org/abs/2509.11217v1,9,2025-09
2,2508.18980,Vanishing Angular Viscosity Limit For Micropol...,"Yinghui Wang, Weihao Zhang",2,We consider the initial-boundary value problem...,2025-08-26,2025-08-26,math.AP,['math.AP'],https://arxiv.org/pdf/2508.18980v1,http://arxiv.org/abs/2508.18980v1,8,2025-08
3,2507.04500,Fast quantum measurement tomography with dimen...,"Leonardo Zambrano, Sergi Ramos-Calderer, Richa...",3,We present a two-step protocol for quantum mea...,2025-07-06,2025-11-28,quant-ph,['quant-ph'],https://arxiv.org/pdf/2507.04500v2,http://arxiv.org/abs/2507.04500v2,7,2025-07
4,2507.07282,Dynamical systems on torus related to general ...,"Artem Alexandrov, Alexey Glutsyuk",2,The overdamped Josephson junction in supercond...,2025-07-09,2025-08-12,math.DS,"['math.DS', 'math-ph', 'nlin.AO']",https://arxiv.org/pdf/2507.07282v3,http://arxiv.org/abs/2507.07282v3,7,2025-07

In [20]:
# Showing the data for fourth Quarter (Oct - Dec)

print(" Q4 (October – December) ")
df_q4.head()

 Q4 (October – December)

,arxiv_id,title,authors,author_count,summary,published,updated,primary_category,categories,pdf_url,entry_id,arxiv_month,arxiv_year_month
0,2512.03699,Transitivity and an abelian Livsic theorem for...,"Mark Pollicott, Richard Sharp",2,We show that the abelian Livšic theorem recent...,2025-12-03,2025-12-03,math.DS,['math.DS'],https://arxiv.org/pdf/2512.03699v1,http://arxiv.org/abs/2512.03699v1,12,2025-12
1,2511.20528,Off-Diagonal Continuous Rado Numbers $x_1 + x_...,"Don Vestal, Jonathan Sax",2,"In 2001, Robertson and Schaal found the 2-colo...",2025-11-25,2025-11-25,math.CO,['math.CO'],https://arxiv.org/pdf/2511.20528v1,http://arxiv.org/abs/2511.20528v1,11,2025-11
2,2512.00480,A Unified Framework for Constructing Informati...,Liang Feng Zhang,1,Retrieving up-to-date information from a publi...,2025-11-29,2025-11-29,cs.CR,"['cs.CR', 'cs.IT']",https://arxiv.org/pdf/2512.00480v1,http://arxiv.org/abs/2512.00480v1,12,2025-12
3,2510.27200,Optical Vortices: Revolutionizing the field of...,"Bikash K. Das, Camilo Granados, Marcelo F. Cia...",3,Light is the fundamental medium through which ...,2025-10-31,2025-12-17,physics.optics,"['physics.optics', 'quant-ph']",https://arxiv.org/pdf/2510.27200v2,http://arxiv.org/abs/2510.27200v2,10,2025-10
4,2511.10391,GrounDiff: Diffusion-Based Ground Surface Gene...,"Oussema Dhaouadi, Johannes Meier, Jacques Kais...",4,Digital Terrain Models (DTMs) represent the ba...,2025-11-13,2025-11-13,cs.CV,['cs.CV'],https://arxiv.org/pdf/2511.10391v1,http://arxiv.org/abs/2511.10391v1,11,2025-11